# Generated by Django 2.2.28 on 2026-03-13 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_on_day', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('is_community', models.BooleanField(default=False)),
                ('habit_type', models.CharField(choices=[('do', 'DO'), ('dont', 'DONT'), ('easy_win', 'EASY_WIN'), ('numeric', 'NUMERIC')], max_length=10)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('about', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nudge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_nudge', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('nudged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_nudge', to='ledger.UserProfile')),
                ('nudger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_nudge', to='ledger.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_text', models.TextField()),
                ('day_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.DayTracker')),
            ],
        ),
        migrations.CreateModel(
            name='HabitTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('habits', models.ManyToManyField(related_name='habit_trackers', to='ledger.Habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_trackers', to='ledger.UserProfile')),
            ],
            options={
                'unique_together': {('user', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_of', to='ledger.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='ledger.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=64)),
                ('date_accepted', models.DateField(blank=True, null=True)),
                ('requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_request', to='ledger.UserProfile')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_request', to='ledger.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='daytracker',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_trackers', to='ledger.HabitTracker'),
        ),
        migrations.CreateModel(
            name='BoolHabitEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('day_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_entries', to='ledger.DayTracker')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Habit')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='daytracker',
            unique_together={('tracker', 'date')},
        ),
    ]
