# Generated by Django 2.2.28 on 2026-03-09 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('is_community', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('do', 'DO'), ('dont', 'DONT'), ('easy_win', 'EASY_WIN'), ('numeric', 'NUMERIC')], max_length=10)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Nudge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_nudge', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('nudged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_nudge', to='ledger.UserProfile')),
                ('nudger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_nudge', to='ledger.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=64)),
                ('date_accepted', models.DateField(blank=True, null=True)),
                ('requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_request', to='ledger.UserProfile')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_request', to='ledger.UserProfile')),
            ],
        ),
    ]
