# Generated by Django 2.2.28 on 2026-03-25 18:06

from django.db import migrations, models
import ledger.models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habittracker',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habittracker',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='guest.jpg', upload_to=ledger.models.user_profile_pic_path),
        ),
    ]
