# Generated by Django 2.2.28 on 2026-03-07 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('is_community', models.BooleanField(default=False)),
                ('habit_type', models.CharField(choices=[('do', 'DO'), ('dont', 'DONT'), ('easy_win', 'EASY_WIN'), ('numeric', 'NUMERIC')], max_length=10)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HabitTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('habits', models.ManyToManyField(to='ledger.Habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.UserProfile')),
            ],
            options={
                'unique_together': {('user', 'month')},
            },
        ),
        migrations.CreateModel(
            name='DayTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_on_day', models.BooleanField(default=False)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.HabitTracker')),
            ],
            options={
                'unique_together': {('tracker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BoolHabitEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('day_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.DayTracker')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Habit')),
            ],
        ),
    ]
