# Generated by Django 2.2.28 on 2026-03-13 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boolhabitentry',
            name='day_tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bool_habit_entries', to='ledger.DayTracker'),
        ),
    ]
