# Generated by Django 2.2.28 on 2026-03-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_auto_20260313_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daytracker',
            old_name='tracker',
            new_name='habit_tracker',
        ),
        migrations.AlterUniqueTogether(
            name='daytracker',
            unique_together={('habit_tracker', 'date')},
        ),
    ]
