# Generated by Django 2.2.28 on 2026-03-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_boolhabitentry_daytracker_habit_habittracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
