# Generated by Django 2.2.28 on 2026-03-21 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_auto_20260313_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habittracker',
            name='month',
            field=models.DateField(default=datetime.datetime(2026, 3, 1, 14, 35)),
        ),
    ]
