# Generated by Django 2.2.28 on 2026-03-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_auto_20260325_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'get_latest_by': 'date'},
        ),
    ]
