# Generated by Django 2.2.28 on 2026-03-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_auto_20260325_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='points',
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_type',
            field=models.CharField(choices=[('do', 'DO'), ('dont', 'DONT'), ('easy_win', 'EASY_WIN')], max_length=10),
        ),
    ]
