# Generated by Django 2.2.28 on 2026-03-22 23:02

from django.db import migrations, models
import ledger.models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_userprofile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=ledger.models.user_profile_pic_path),
        ),
    ]
