# Generated by Django 2.2.28 on 2026-03-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_auto_20260313_1357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DayTracker',
            new_name='Day',
        ),
    ]
