# Generated by Django 2.2.28 on 2026-03-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_auto_20260326_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
