# Generated by Django 2.2.28 on 2026-03-21 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_auto_20260321_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habittracker',
            name='month',
            field=models.DateField(default=datetime.datetime(2026, 3, 1, 21, 25)),
        ),
    ]
