# Generated by Django 2.2.28 on 2026-03-21 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_auto_20260321_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='ledger.HabitTracker'),
        ),
    ]
