# Generated by Django 2.2.28 on 2026-03-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_auto_20260326_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
