# Generated by Django 2.2.28 on 2026-03-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_habit_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_type',
            field=models.CharField(choices=[('do', 'DO'), ('dont', 'DONT'), ('easy_win', 'EASY_WIN'), ('numeric', 'NUMERIC')], max_length=10),
        ),
    ]
