# Generated by Django 2.2.28 on 2026-03-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_auto_20260321_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='tracker',
            new_name='habit_tracker',
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('habit_tracker', 'date')},
        ),
    ]
