# Generated by Django 2.2.28 on 2026-03-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_auto_20260326_1804'),
        ('ledger', '0003_auto_20260326_1611'),
    ]

    operations = [
    ]
