# Generated by Django 2.2.28 on 2026-03-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_auto_20260321_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boolhabitentry',
            old_name='day_tracker',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='journalentry',
            old_name='day_tracker',
            new_name='day',
        ),
    ]
