# Generated by Django 2.2.28 on 2026-03-26 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_merge_20260326_1944'),
        ('ledger', '0004_auto_20260326_1911'),
    ]

    operations = [
    ]
