# Generated by Django 2.2.28 on 2026-03-21 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_auto_20260321_1205'),
    ]

    operations = [
    ]
