# Generated by Django 2.2.28 on 2026-03-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_merge_20260326_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
