# Generated by Django 2.2.28 on 2026-03-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_merge_20260321_2243'),
        ('ledger', '0004_auto_20260321_2125'),
    ]

    operations = [
    ]
