# Generated by Django 2.2.28 on 2026-03-22 15:15

from django.db import migrations, models
import ledger.utils.date_utils


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_merge_20260322_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habittracker',
            name='month',
            field=models.DateField(default=ledger.utils.date_utils.get_first_of_this_month),
        ),
    ]
