# Generated by Django 2.2.28 on 2026-03-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_auto_20260326_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_type',
            field=models.CharField(choices=[('do', 'Dos'), ('dont', "Don'ts"), ('easy_win', 'Easy Wins'), ('numeric', 'Numeric')], max_length=10),
        ),
    ]
