# Generated by Django 2.2.28 on 2026-03-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_auto_20260322_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habittracker',
            name='habits',
            field=models.ManyToManyField(to='ledger.Habit'),
        ),
    ]
