# Generated by Django 2.2.28 on 2026-03-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_auto_20260322_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habittracker',
            name='habits',
            field=models.ManyToManyField(related_name='habits', to='ledger.Habit'),
        ),
    ]
