# Generated by Django 2.2.28 on 2026-03-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_auto_20260322_1520'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habit',
            unique_together={('name', 'habit_type')},
        ),
    ]
