from django.test import TestCase

# ---------- models -----------
from django.contrib.auth.models import User
from ledger.models import Habit, HabitTracker, DayTracker
from ledger.models import UserProfile

import factory

# --------- misc -------------
from datetime import datetime

# helper
def get_first_of_month():
    return datetime.today().replace(day=1)

# factory for base user model (not used directly)
class UserFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = User
    username = "test"


class UserProfileFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = UserProfile
    # use subfactory for dependent models
    user = factory.SubFactory(UserFactory)

class HabitFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Habit
    is_community = True
    habit_type = Habit.TYPE_DO
    points = 10

class HabitTrackerFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = HabitTracker
    user = factory.SubFactory(UserProfileFactory)
    # lazy = only call when necessary
    month = factory.LazyFunction(get_first_of_month)
    # add habits once initialised...

class DayTrackerFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = DayTracker
    tracker = factory.SubFactory(HabitTrackerFactory)
    date = factory.LazyFunction(datetime.today)
    completed_on_day = True


class HabitTests(TestCase):
    def test_create_habit(self):
        # check can create habit (use factory)
        _ = HabitFactory()
        self.assertTrue(Habit.objects.exists())

    def test_user_associated_habits(self):
        test_habit = HabitFactory(name="Sleep 10hrs")
        self.assertEqual(Habit.objects.get(name="Sleep 10hrs"), test_habit)

class HabitTrackerTests(TestCase):
    def test_create_HabitTracker(self):
        _ = HabitTrackerFactory()
        self.assertTrue(HabitTracker.objects.exists())

    def test_get_habit_tracker_user(self):
        user = UserProfileFactory()
        tracker = HabitTrackerFactory(user=user)
        # test that user associated habit is actually the ht generated by factory
        self.assertEqual(HabitTracker.objects.get(user=user), tracker)

class DayTrackerTests(TestCase):
    def test_create_DayTracker(self):
        _ = DayTrackerFactory()
        self.assertTrue(DayTracker.objects.exists())

    def test_get_habit_tracker_days_underscore_set(self):
        ht = HabitTrackerFactory()
        day = DayTrackerFactory(tracker=ht)
        # use _set syntax to test
        self.assertEqual(ht.daytracker_set.all()[0], day)

    def test_get_habit_tracker_days_filter(self):
        ht = HabitTrackerFactory()
        day = DayTrackerFactory(tracker=ht)
        # get first filtered object
        self.assertEqual(DayTracker.objects.filter(tracker=ht)[0], day)

