from django.test import TestCase

# ---------- models -----------
from ledger.models import Habit, HabitTracker, Day
from .test_factories import *

# utils
from ledger.utils import date

class HabitTests(TestCase):
    def test_create_habit(self):
        # check can create habit (use factory)
        _ = HabitFactory()
        self.assertTrue(Habit.objects.exists())

    def test_habit_has_correct_type(self):
        _ = HabitFactory()
        self.assertEqual(Habit.objects.first().habit_type, Habit.TYPE_DO)

    def test_habit_is_community(self):
        _ = HabitFactory()
        self.assertEqual(Habit.objects.first().is_community, True)

    def test_user_associated_habits(self):
        test_habit = HabitFactory(name="Sleep 10hrs")
        self.assertEqual(Habit.objects.get(name="Sleep 10hrs"), test_habit)

class HabitTrackerTests(TestCase):
    def test_create_HabitTracker(self):
        _ = HabitTrackerFactory()
        self.assertTrue(HabitTracker.objects.exists())

    def test_habit_tracker_user_is_correct(self):
        user = UserProfileFactory()
        habit_tracker = HabitTrackerFactory(user=user)
        # test that user associated habit is actually the ht generated by factory
        self.assertEqual(user.habit_trackers.first(), habit_tracker)

    def test_habit_tracker_month_is_correct(self):
        habit_tracker = HabitTrackerFactory()
        self.assertEqual(habit_tracker.month, date.get_first_of_this_month())

class DayTests(TestCase):
    def test_create_Day(self):
        _ = DayFactory()
        self.assertTrue(Day.objects.exists())

    def test_get_habit_tracker_days_underscore_set(self):
        ht = HabitTrackerFactory()
        day = DayFactory(habit_tracker=ht)
        # use _set syntax to test
        self.assertEqual(ht.days.first(), day)

    def test_get_habit_tracker_days_filter(self):
        ht = HabitTrackerFactory()
        day = DayFactory(habit_tracker=ht)
        # get first filtered object
        self.assertEqual(ht.days.first(), day)

class BoolHabitEntryTests(TestCase):
    def test_create_bool_habit_entry(self):
        _ = BoolHabitEntryFactory()
        self.assertTrue(BoolHabitEntry.objects.exists())

    def test_add_habit_entries_to_days_then_get_habit_entries_for_day(self):
        day = DayFactory()
        habit_entry = BoolHabitEntryFactory(day=day)
        self.assertEquals(day.bool_habit_entries.first(), habit_entry)

