from django.test import TestCase

# ---------- models -----------
from ledger.models import Habit, HabitTracker, DayTracker
from .test_factories import *

class HabitTests(TestCase):
    def test_create_habit(self):
        # check can create habit (use factory)
        _ = HabitFactory()
        self.assertTrue(Habit.objects.exists())

    def test_user_associated_habits(self):
        test_habit = HabitFactory(name="Sleep 10hrs")
        self.assertEqual(Habit.objects.get(name="Sleep 10hrs"), test_habit)

class HabitTrackerTests(TestCase):
    def test_create_HabitTracker(self):
        _ = HabitTrackerFactory()
        self.assertTrue(HabitTracker.objects.exists())

    def test_get_habit_tracker_user(self):
        user = UserProfileFactory()
        tracker = HabitTrackerFactory(user=user)
        # test that user associated habit is actually the ht generated by factory
        self.assertEqual(HabitTracker.objects.get(user=user), tracker)

class DayTrackerTests(TestCase):
    def test_create_DayTracker(self):
        _ = DayTrackerFactory()
        self.assertTrue(DayTracker.objects.exists())

    def test_get_habit_tracker_days_underscore_set(self):
        ht = HabitTrackerFactory()
        day = DayTrackerFactory(tracker=ht)
        # use _set syntax to test
        self.assertEqual(ht.daytracker_set.all()[0], day)

    def test_get_habit_tracker_days_filter(self):
        ht = HabitTrackerFactory()
        day = DayTrackerFactory(tracker=ht)
        # get first filtered object
        self.assertEqual(DayTracker.objects.filter(tracker=ht)[0], day)

